baseURL = "https://pyrimoto.com/"
title = "Pyrimoto"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

enableRobotsTXT = true

[languages]

  [languages.ca]
    label = "Català"
    locale = "ca"
    weight = 2

  [languages.es]
    label = "Castellano"
    locale = "es"
    weight = 3

  [languages.en]
    label = "English"
    locale = "en"
    weight = 1

  [languages.fr]
    label = "Français"
    locale = "fr"
    weight = 4

  [languages.de]
    label = "Deutsch"
    locale = "de"
    weight = 5

[params]
  description = "Viatges guiats amb moto pels millors paisatges i carreteres dels Pirineus."
  author = "Pyrimoto"
  images = ["images/home/hero.jpg"]
