baseURL = "https://pyrimoto.com/"
title = "Pyrimoto"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

enableRobotsTXT = true

[languages.ca]
  label = "Català"
  locale = "ca"
  weight = 2

  [languages.ca.params]
    description = "Viatges guiats amb moto pels millors paisatges i carreteres dels Pirineus."

[languages.es]
  label = "Castellano"
  locale = "es"
  weight = 3

  [languages.es.params]
    description = "Viajes guiados en moto por los mejores paisajes y carreteras de los Pirineos."

[languages.en]
  label = "English"
  locale = "en"
  weight = 1

  [languages.en.params]
    description = "Guided motorcycle tours through the best roads and landscapes of the Pyrenees."

[languages.fr]
  label = "Français"
  locale = "fr"
  weight = 4

  [languages.fr.params]
    description = "Voyages guidés à moto sur les plus belles routes et à travers les paysages des Pyrénées."

[languages.de]
  label = "Deutsch"
  locale = "de"
  weight = 5

  [languages.de.params]
    description = "Geführte Motorradreisen auf den schönsten Straßen und durch die Landschaften der Pyrenäen."

[params]
  author = "Pyrimoto"
  images = ["images/home/hero.jpg"]
